#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2019.4.40f1_ffc62b691db5"
#define UNITY_VERSION_FULL_NICE "2019.4.40f1 (ffc62b691db5)"
#define UNITY_VERSION_BLD 16762411
#define UNITY_VERSION_DATE 1654718189
#define UNITY_VERSION_WIN "2019.4.40.16762411"
#define UNITY_VERSION_BRANCH "2019.4/staging"
